### ISSUE TITLE
Release to haxelib

### ISSUE THREAD

**Issue by CrazyFlasher** [andrew-git/StarlingGAFPlayerOpenFL#1]
Hi, can you release to haxelib?
If you don't want, I can fork it and do it myself, if you don't mind

**Comment by andrew-git** [comment]
Hi
I should register somewhere to release to haxelib?

**Comment by CrazyFlasher** [comment]
https://lib.haxe.org/documentation/using-haxelib/
Check `haxelib submit` and `haxelib register` commands

**Comment by andrew-git** [comment]
Thanks, will do in few days
